apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "webbackend.fullname" . }}-ingressroutebar
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`{{ .Release.Name }}.{{  .Values.global.root_domain }}`) && PathPrefix(`/webbackend/`)
    kind: Rule
    services:
    - name: {{ include "webbackend.fullname" . }}-service
      port: {{ .Values.service.port }}
    middlewares:
    - name: {{ include "webbackend.fullname" . }}-middleware