apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "webbackend.fullname" . }}-middleware
spec:
  stripPrefix:
    prefixes:
      - /{{ include "webbackend.name" . }}