apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "gw-midstage-web.fullname" . }}-ingressroutebar
spec:
  entryPoints:
    - websecure
    - web
  routes:
  - match: Host(`{{if not .Values.global.product }}{{ .Release.Name }}.{{end}}{{  .Values.global.root_domain }}`) && PathPrefix(`/gw-midstage`)
    kind: Rule
    services:
    - name: {{ include "gw-midstage-web.fullname" . }}-service
      port: {{ .Values.service.port }}
  tls: {}