apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "gateway-web.fullname" . }}-ingressroutebar
spec:
  entryPoints:
    - websecure
    - web
  routes:
  - match: Host(`{{if not .Values.global.product }}{{ .Release.Name }}.{{end}}{{  .Values.global.root_domain }}`) && PathPrefix(`/gateway/`)
    kind: Rule
    services:
    - name: {{ include "gateway-web.fullname" . }}-service
      port: 8080
  tls: {}