apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: pinpoint-collector
  name: pinpoint-collector
spec:
  replicas: 1
  selector:
    matchLabels:
    io.kompose.service: pinpoint-collector
  template:
    metadata:
      labels:
        io.kompose.service: pinpoint-collector
    spec:
      containers:
      - env:
        - name: HBASE_HOST
          value: pinpoint-hbase.default.svc.cluster.local
        - name: HBASE_PORT
          value: '2181'
        image: pinpointdocker/pinpoint-collector:{{ .Values.image.tag }}
        name: pinpoint-collector
        ports:
        - containerPort: 9994
        - containerPort: 9995
        - containerPort: 9996
        - containerPort: 9995
          protocol: UDP
        - containerPort: 9996
          protocol: UDP
      restartPolicy: Always
