apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: pinpoint-hbase
  name: pinpoint-hbase
spec:
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: pinpoint-hbase
    spec:
      containers:
      - image: pinpointdocker/pinpoint-hbase:{{ .Values.image.tag }}
        name: pinpoint-hbase
        ports:
        - containerPort: 2181
        - containerPort: 60000
        - containerPort: 16010
        - containerPort: 60020
        - containerPort: 16030
        resources: {}
        # volumeMounts:
        # - {mountPath: /home/pinpoint/hbase, name: pinpoint-hbase-claim0}
        # - {mountPath: /home/pinpoint/zookeeper, name: pinpoint-hbase-claim1}
      restartPolicy: Always
      # volumes:
      # - name: pinpoint-hbase-claim0
      #   persistentVolumeClaim: {claimName: pinpoint-hbase-claim0}
      # - name: pinpoint-hbase-claim1
      #   persistentVolumeClaim: {claimName: pinpoint-hbase-claim1}
status: {}
