apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: pinpoint-web
  name: pinpoint-web
spec:
  type: NodePort
  ports:
  - name: "9997"
    port: 9997
    targetPort: 9997
    nodePort: 9997
  - name: "8080"
    port: 8080
    targetPort: 8080
    nodePort: 8080
  selector:
    io.kompose.service: pinpoint-web
