apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  
  labels:
    io.kompose.service: pinpoint-hbase-claim0
  name: pinpoint-hbase-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10000Mi
status: {}
