apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: pinpoint-hbase
  name: pinpoint-hbase
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pinpoint-hbase
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pinpoint-hbase
    spec:
      hostname: pinpoint-hbase
      containers:
      - image: pinpointdocker/pinpoint-hbase:{{ .Values.image.tag }}
        name: pinpoint-hbase
        ports:
        - containerPort: 2181
        - containerPort: 60000
        - containerPort: 16010
        - containerPort: 60020
        - containerPort: 16030
        volumeMounts:
          - mountPath: /home/pinpoint/hbase
            name: pinpoint-hbase-data
          - mountPath: /home/pinpoint/zookeeper
            name: pinpoint-hbase-zk
      restartPolicy: Always
      volumes:
        - name: pinpoint-hbase-data
          persistentVolumeClaim:
            claimName: pinpoint-hbase-data
        - name: pinpoint-hbase-zk
          persistentVolumeClaim:
            claimName: pinpoint-hbase-zk
status: {}
