apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: pinpoint-web
  name: pinpoint-web
spec:
  type: ClusterIP
  ports:
  - name: "9997"
    port: 9997
    targetPort: 9997
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: pinpoint-web
