apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.18.0
  
  labels:
    io.kompose.service: pinpoint-web
  name: pinpoint-web
spec:
  type: NodePort
  ports:
  - name: "9997"
    port: 9997
    targetPort: 9997
    nodePort: 30001
  - name: "8080"
    port: 8080
    targetPort: 8080
    nodePort: 30000
  selector:
    io.kompose.service: pinpoint-web
