apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.18.0
  labels:
    io.kompose.service: pinpoint-collector
  name: pinpoint-collector
spec:
  type: NodePort
  ports:
  - name: "9994"
    port: 9994
    targetPort: 9994
    nodePort: 30002
  - name: "9995"
    port: 9995
    targetPort: 9995
    nodePort: 30003
    protocol: UDP 
  - name: "9996"
    port: 9996
    targetPort: 9996
    nodePort: 30004
    protocol: UDP
  selector:
    io.kompose.service: pinpoint-collector
status:
  loadBalancer: {}
