apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: pinpoint-hbase-claim1
  name: pinpoint-hbase-claim1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10000Mi
