apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: pinpoint-collector
  name: pinpoint-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pinpoint-collector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pinpoint-collector
    spec:
      hostname: pinpoint-collector
      containers:
      - env:
        - name: HBASE_HOST
          value: pinpoint-hbase.default.svc.cluster.local
        - name: HBASE_PORT
          value: '2181'
        image: pinpointdocker/pinpoint-collector:{{ .Values.image.tag }}
        name: pinpoint-collector
        ports:
        - containerPort: 9994
        - containerPort: 9995
        - containerPort: 9996
      restartPolicy: Always
