apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: pinpoint-collector
  name: pinpoint-collector
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: "9994"
    port: 9994
    targetPort: 9994
  - name: "9995"
    port: 9995
    targetPort: 9995
    protocol: UDP
  - name: "9996"
    port: 9996
    targetPort: 9996
    protocol: UDP
  selector:
    app.kubernetes.io/name: pinpoint-collector
status:
  loadBalancer: {}
