apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: pinpoint-web
  name: pinpoint-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pinpoint
  template:
    metadata:
      labels:
        io.kompose.service: pinpoint-web
    spec:
      containers:
      - image: pinpointdocker/pinpoint-web:{{ .Values.image.tag }}
        name: pinpoint-web
        ports:
        - containerPort: 9997
        - containerPort: 8080
        env:
        - name: HBASE_HOST
          value: "pinpoint-hbase.default.svc.cluster.local"
        - name: HBASE_PORT
          value: "2181"
      restartPolicy: Always
