apiVersion: apps/v1beta1
kind: Deployment
metadata:
  annotations: {kompose.cmd: kompose convert -c, kompose.version: 1.18.0}
  labels: {io.kompose.service: pinpoint-collector}
  name: pinpoint-collector
spec:
  replicas: 1
  template:
    metadata:
      labels: {io.kompose.service: pinpoint-collector}
    spec:
      containers:
      - env:
        - {name: HBASE_HOST, value: pinpoint-hbase.default.svc.cluster.local}
        - {name: HBASE_PORT, value: '2181'}
        image: 192.168.6.11/clv/pinpoint-collector
        name: pinpoint-collector
        ports:
        - {containerPort: 9994}
        - {containerPort: 9995}
        - {containerPort: 9996}
        - {containerPort: 9995, protocol: UDP}
        - {containerPort: 9996, protocol: UDP}
        resources: {}
      restartPolicy: Always
