---
apiVersion: v1
kind: Service
metadata:
  name: disconf-svc
  labels:
    app: disconf
spec:
  ports:
  - port: 8091
    name: server
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: disconf
  labels:
    app: disconf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: disconf
  template:
    metadata:
      labels:
        app: disconf
    spec:
      containers:
      - name: disconf
        imagePullPolicy: Always
        #image: harbor.clvpg.com/clv/disconf:latest
        image: habor.clvpg.com/clv/disconf:latest
        ports:
        - containerPort: 8080
          name: disconf
      - name: nginx
        imagePullPolicy: Always
        #image: harbor.clvpg.com/clv/disconf:latest
        image: habor.clvpg.com/clv/disconf_nginx:latest
        ports:
        - containerPort: 8091
          name: nginx
      nodeSelector:
        kubernetes.io/hostname: k8ss4