apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "webmobile.fullname" . }}-middleware
spec:
  stripPrefix:
    prefixes:
      - /{{ include "webmobile.name" . }}