# Default values for iot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

metrics:
  enabled: true

mysqlRootPassword: 123123aa

persistence:
  enabled: true
  size: 50Gi

nodeSelector: {}

tolerations: []

affinity: {}
