# Default values for iot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


mysqlha:
  replicaCount: 2

metrics:
  enabled: true

mysqlRootPassword: 123123aa

persistence:
  enabled: true
  storageClass: local-storage
  volumeName: mysql-pvc
  size: 50Gi

nodeSelector:
  kubernetes.io/hostname: k8ss3

tolerations: []

affinity: {}
