kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-redis-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage


---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-redis-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-redis-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage