#------------------------------------------------------------------------------
# Disconf:
#------------------------------------------------------------------------------
disconf:
  image: "harbor.lifesense.com/lifesense/disconf"
  imageTag: "v0.0.2"
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
nginx:
  image: "harbor.lifesense.com/library/nginx"
  imageTag: "1.11.4-alpine"
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
replicas: 1
DISCONF_DOAMIN: disconf-th2.lifesense.com
#mail
EMAIL_MONITOR_ON: true
EMAIL_HOST: smtp.163.com
EMAIL_HOST_PASSWORD: password
EMAIL_HOST_USER: sender@163.com
EMAIL_PORT: 25
DEFAULT_FROM_EMAIL: disconf@163.com

imagePullPolicy: Always
service:
  externalPort: 80
ingress:
  enabled: true
  hosts: 
  - disconf-th2.lifesense.com
