apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "webpgh5.fullname" . }}-ingressroutebar
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`{{if not .Values.global.product }}{{ .Release.Name }}.{{end}}{{  .Values.global.root_domain }}`) && PathPrefix(`/app/clvpg`)
    kind: Rule
    services:
    - name: {{ include "webpgh5.fullname" . }}-service
      port: {{ .Values.service.port }}
    middlewares:
    - name: {{ include "webpgh5.fullname" . }}-middleware