apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "datasync-web.fullname" . }}-ingressroutebar
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`{{ .Release.Name }}.{{  .Values.global.root_domain }}`) && PathPrefix(`/datasync/`)
    kind: Rule
    services:
    - name: {{ include "datasync-web.fullname" . }}-service
      port: 8080