
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emqx
  labels:
    app: emqx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emqx
  template:
    metadata:
      labels:
        app: emqx
    spec:
      containers:
      - name: emqx
        imagePullPolicy: Always
        image: emqx/emqx
        ports:
        - containerPort: 18083
          name: dashboard
        - containerPort: 1883
          name: mqtt
      nodeSelector:
        kubernetes.io/hostname: k8ss4

---
apiVersion: v1
kind: Service
metadata:
  name: emqx-svc
  labels:
    app: emqx
spec:
  ports:
    - port: 18083
      name: dashboard
      targetPort: 18083
    - port: 1883
      name: mqtt
      targetPort: 1883
  clusterIP: None
  selector:
    app: emqx



---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: emqx-dashboard-ingressroute
spec:
  entryPoints:
    - websecure
    - web
  routes:
    - match: Host(`emqx.clvpg.com`)
      kind: Rule
      services:
        - name: emqx-svc
          port: 18083
          scheme: http

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: emqx-mqtt-ingressroute
spec:
  entryPoints:
    - emqx
  routes:
    - match: HostSNI(`*`)
      kind: Rule
      services:
        - name: emqx-svc
          port: 1883
