apiVersion: v1
kind: Service
metadata:
  name: {{ template "zookeeper.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "zookeeper.labels" . | nindent 4 }}
    app.kubernetes.io/component: zookeeper
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: tcp-client
      port: 2181
      targetPort: client
    - name: tcp-follower
      port: 2888
      targetPort: follower
    - name: tcp-election
      port: 3888
      targetPort: election
  selector: {{- include "zookeeper.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: zookeeper
