kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zookeep-node1-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage


---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zookeep-node2-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zookeep-node3-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage